### ISSUE TITLE
Nouvel écran de résultat pour le parcours gestes

### ISSUE THREAD

**Issue by laem** [betagouv/reno#27]
À l'instar de l'écran accompagné, après que l'utilisateur a sélectionné ses gestes, lui expliquer le total, lui poser les questions (surface), lui parler TVA (par exemple), etc. 

Tester sans montant dans le panier, juste le nombre de gestes sélectionnés sur l'écran 1. Mettre la somme sur le 2 quand l'utilisateur a saisi les données supplémentaires : m² et nombre de fenêtres.

```[tasklist]
### Tasks
- [x] deuxième écran panier
- [x] bouton "tout décocher"
- [x] gestion du flou et des questions restantes sur le deuxième écran
- [x] avertissement pour les conditions "chauffage décarboné obligatoire"
- [x] affichage des conditions (RGE / pas RGE) avant un bouton CTA "Contacter France Renov"
- [x] s'assurer que ça fonctionne bien sur mobile
```

**Comment by laem** [comment]
![2024-02-20-11-16-02-338](https://github.com/betagouv/reno/assets/1177762/16a8fed5-2279-47c3-abd5-8b5c4c89753d)

**Comment by laem** [comment]
Tester sans montant dans le panier, juste le nombre de gestes sélectionnés sur l'écran 1. Mettre la somme sur le 2 quand l'utilisateur a saisi les données supplémentaires : m² et nombre de fenêtres.

- [ ] bouton "tout décocher"

**Comment by laem** [comment]
- [ ] bloquer le "suivant" si condition non satisfaite
- [ ] trouver mieux que l'effet Mitterand, le flou perturbe quand on connait pas le filter: blur

**Comment by laem** [comment]
C'est fait :)
